name: Lint and Build GTN

# https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#example-using-a-list-of-events
on: [push]

jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: true
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Install
        run: |
          pip install asciinema
          sudo apt-get install pv

      - name: Record
        run: |
          asciinema rec gh.cast -c ./demo.sh
        env:
            TERM: xterm


      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: asciinema-cast
          path: gh.cast
