name: Auto GAT CVMFS

on: [push]

jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: true

      # BEGIN Dependencies
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7"
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/cache@v2
        with:
          path: |
            vendor/bundle
            ~/.npm
          key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: |
            pip install -r requirements.txt
            npm i

      - name: Install system dependencies
        run: |
            sudo apt install -y pkg-config xvfb libx11-dev libxi-dev libxext-dev libglx-dev libglu1-mesa-dev freeglut3-dev mesa-common-dev ffmpeg pv silversearcher-ag fonts-dejavu-core fonts-dejavu-extra curl acl

            npx -y playwright install-deps chromium

          wget https://github.com/cirocosta/asciinema-edit/releases/download/0.0.6/asciinema-edit_0.0.6_linux_amd64.tar.gz
          tar xvfz asciinema-edit_0.0.6_linux_amd64.tar.gz

          git clone https://github.com/hexylena/git-gat/ ~/galaxy/
      # END Dependencies

      - name: Auth to asciinema
        run: |
            mkdir -p ~/.config/asciinema/
            echo "${ASCIINEMA_KEY}" >> ~/.config/asciinema/install-id
        env:
            ASCIINEMA_KEY: ${{ secrets.ASCIINEMA_KEY }}

      #- name: Record & Upload
        #shell: 'script --return --quiet --command "bash {0}"'
        #run: |
          #stty cols 174 rows 35
          #asciinema rec gh.cast -c ./demo.sh -t "Automated Github Recording $(date)"
          #./asciinema-edit quantize --range 5 gh.cast > gh-short.cast
          #asciinema upload gh-short.cast
        #env:
            #TERM: xterm
